name: Build and Check

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-with-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - uses: Mic92/hestia@v3

      - name: Build RISC-V Binary
        run: nix develop --command sh -c "cmake -B build && cmake --build build --verbose"

      - name: Run Test
        run: nix develop --command qemu-riscv64 build/test day4sample.txt || true

  check-without-nix:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - uses: actions/checkout@v7

      - name: Install Dependencies via apt
        run: |
          apt-get update
          apt-get install -y \
            cmake \
            clang \
            binutils-riscv64-unknown-elf \
            qemu-user \
            make

      - name: Build RISC-V Binary
        run: cmake -B build && cmake --build build --verbose

      - name: Run Test
        run: qemu-riscv64 build/test day4sample.txt || true